### PR TITLE
add new songs

### PR DESCRIPTION
**Pull request by jacobvr**

### CODE REVIEW

**Comment by jacobvr** [comment]
@maxned I did not check every single line here, the goal of this PR is just to make sure we are safe to run our script

**Review by maxned — CHANGES_REQUESTED** [review]
Could you do only the songs that overlap with those that we do at church? Also, I think "In Christ Alone" is missing.

**Comment by jacobvr** [comment]
If I understand you correctly, do you want me to add chords to the songs we sing in church? For the songs I have the chords, right?

**Comment by maxned** [comment]
Yes, that’s right. Then I can run my script and it won’t delete the chords for the songs I have. It won’t touch the songs that aren’t script managed.

Thanks,
Max.

**Pull request closed without merging**
